from selenium import webdriver
from selenium.webdriver.common.by import By
driver = webdriver.Firefox()

class OrderFormLocators:
    NAME = (By.XPATH, "//input[@placeholder='* Имя']")
    LASTNAME = (By.XPATH, "//input[@placeholder='* Фамилия']")
    ADDRESS = (By.XPATH, "//input[@placeholder='* Адрес: куда привезти заказ']")
    METRO_STATION = (By.XPATH, "//input[@placeholder='* Станция метро']")
    METRO_STATION_SELECTOR_LOCATOR = (By.XPATH, "//div[@class='select-search__select']//li")
    PHONE = (By.XPATH, "//input[@placeholder='* Телефон: на него позвонит курьер']")
    NEXT_BUTTON = (By.XPATH, "//button[@class='Button_Button__ra12g Button_Middle__1CSJM']")
    CALENDAR = (By.XPATH, "//div[contains(@class, '__day--today')]")
    WHEN_TO_DELIVER = (By.XPATH, '//input[@placeholder="* Когда привезти самокат"]')
    RENTAL_PERIOD = (By.CLASS_NAME, "Dropdown-placeholder")
    RENTAL_PERIOD_DROPDOWN_MENU = (By.CLASS_NAME, "Dropdown-menu")
    RENTAL_PERIOD_OPTIONS = (By.XPATH, "//*[contains(@class, 'Dropdown-option')]")
    COMMENT = (By.XPATH, '//input[@placeholder="Комментарий"]')
    SCOOTER_COLOR = (By.CLASS_NAME, "Checkbox_Input__14A2w")
    ORDER_BUTTON = (By.XPATH, '//button[text()="Заказать"]')
    YES_BUTTON = (By.XPATH, '//button[text()="Да"]')
    SUCCESS_MESSAGE = (By.CLASS_NAME, "Order_Text__2broi")
    ERROR_MESSAGE = (By.XPATH, "//div[@class='Input_ErrorMessage__3HvIb Input_Visible___syz6']")
    ORDER_CONFIRMATION = (By.CLASS_NAME, "Order_Modal__YZ-d3")
    YANDEX_LOGO = (By.XPATH, "//img[@alt='Yandex']")
    SCOOTER_LOGO = (By.XPATH, "//img[@alt='Scooter']")
    HEADER_ORDER_BUTTON = (By.XPATH, '//button[text()="Заказать"]')
    FOOTER_ORDER_BUTTON = (By.CLASS_NAME, 'Button_Button__ra12g Button_Middle__1CSJM')